### ISSUE TITLE
The tiktok dataset

### ISSUE THREAD

**Issue by WillowKaze** [HKUDS/MMSSL#1]
I will appreciate your great work on multi-modal recommendation！I am trying to work on the multimodal encoding, so I just want to see it can achieve higher performance with other feature extractor. I am wondering is it possible to get access to the raw data? Thank you!

**Comment by weiwei1206** [comment]
Amazon-baby/sports:  http://jmcauley.ucsd.edu/data/amazon/links.html
Tiktok: Please refer to "MMGCN: Multi-modal Graph Convolution Network for Personalized Recommendation of Micro-video"
Allrecipes:  Please refer to "Hierarchical Attention Network for Visually-aware Food Recommendation"

**Comment by weiwei1206** [comment]
> I will appreciate your great work on multi-modal recommendation！I am trying to work on the multimodal encoding, so I just want to see it can achieve higher performance with other feature extractor. I am wondering is it possible to get access to the raw data? Thank you!

Amazon-baby/sports: http://jmcauley.ucsd.edu/data/amazon/links.html
Tiktok: Please refer to "MMGCN: Multi-modal Graph Convolution Network for Personalized Recommendation of Micro-video"
Allrecipes: Please refer to "Hierarchical Attention Network for Visually-aware Food Recommendation"

**Comment by weiwei1206** [comment]
The official website of the ‘Tiktok’ dataset has been closed. Thus, we also provide a 'large version' of the preprocessed [Tiktok-70710](https://pan.baidu.com/s/10hhz1y7__XixcLo7MCTByQ?pwd=wiak) (Code: wiak). Again, we spent a lot of time pre-processing this dataset, so if you use our preprocessed Tiktok dataset in your work please cite our paper.
