### ISSUE TITLE
Some questions about your `Multi-Modal High-Order Connectivity` module.

### ISSUE THREAD

**Issue by liuxianyi** [HKUDS/MMSSL#11]
An excellent paper, but I was confused by your module `Multi-Modal High-Order Connectivity`:
![截屏2023-06-05 17 38 50](https://github.com/HKUDS/MMSSL/assets/33951338/eaf307de-56e6-4922-afa8-00cff0d1dda5)
In this formula,  If I have deduced correctly, $\hat{E}_u^l$ is from the output of `modality-wise Dependency Modeling`. 
Its dimension is $m \times d$, supposing that $m$ is the nums of users. The $A \in \mathbb{R}^{n \times m}$ is the user-inter interactive matrix, and $n$ denotes the item nums. From those, it is inferred that the dimension of the output representations $\hat{E}_u^{l+1}$  is $n \times d$, which is corresponding to the representations of items but users. 
So, Can help me solve my confusion？ thanks.

**Comment by weiwei1206** [comment]
Thank you for your interest in our work~

Based on your feedback, the draft has been updated, and the revised version will soon be available on arXiv. We sincerely appreciate your support and feedback.
