### ISSUE TITLE
Raw Data

### ISSUE THREAD

**Issue by XiaoxinHe** [HKUDS/MMSSL#14]
Thanks for the great work!

I noticed that you have provided the processed feature. I am wondering if the raw data (such as the images, videos, and text) will be made publicly available? Thanks!

**Comment by weiwei1206** [comment]
Your interest in our work is deeply appreciated. Regrettably, we are currently unable to furnish the original TikTok dataset. However, we have recently curated a multimodal dataset from 🚀Netflix🚀, incorporating both textual and visual elements. You are cordially invited to make use of this resource🤝🤝.
