### ISSUE TITLE
About Dataset Question

### ISSUE THREAD

**Issue by sun2ot** [HKUDS/MMSSL#20]
Thank you for your hard work and dedication. I want to know how to load dataset such as `augmented_attribute_dict` in your google share drive?

**Comment by sun2ot** [comment]
OK... I got the answer through trying, it's `pickle`.

**Comment by Gs0098** [comment]
> Thank you for your hard work and dedication. I want to know how to load dataset such as `augmented_attribute_dict` in your google share drive?感谢您的辛勤工作和奉献。我想知道如何加载像 `augmented_attribute_dict` 这样的数据集到您的谷歌共享驱动器中？

The translation of "请问如何获取论文中的数据集" into English is:

"How can I obtain the dataset used in the paper?"
