### ISSUE TITLE
Processed data about Allrecipes

### ISSUE THREAD

**Issue by shentt67** [HKUDS/MMSSL#4]
Thanks for your excellent work! Can you please share the processed data of Allrecipes Dataset? I can not find it on the shared Google Drive link.

**Comment by weiwei1206** [comment]
Sorry for the inconvenience, all datasets have been uploaded.

**Comment by shentt67** [comment]
Thanks. I have problems with the codes and need your help. When I run the codes on TikTok datasets, the recall value remains 0. 
Here are parts of  the training logs:
2023-03-23 22:09:  Epoch 33 [21.8s]: train==[28.17953=1.30388 + 0.01747 + 0.00000  + 0.00000]
2023-03-23 22:09:  Epoch 33 [21.8s + 0.5s]: train==[28.17953=1.30388 + 0.01747 + 0.00000], recall=[0.00000, 0.00000, 0.00000], precision=[0.00000, 0.00000, 0.00000], hit=[0.00000, 0.00000, 0.00000], ndcg=[0.00000, 0.00000, 0.00000]
2023-03-23 22:09:  #####Early stopping steps: 34 #####
(I only change the 'early_stopping_patience', all the codes are the same as that on the repository)
Can you help me?

**Comment by weiwei1206** [comment]
> Thanks. I have problems with the codes and need your help. When I run the codes on TikTok datasets, the recall value remains 0. Here are parts of the training logs: 2023-03-23 22:09: Epoch 33 [21.8s]: train==[28.17953=1.30388 + 0.01747 + 0.00000 + 0.00000] 2023-03-23 22:09: Epoch 33 [21.8s + 0.5s]: train==[28.17953=1.30388 + 0.01747 + 0.00000], recall=[0.00000, 0.00000, 0.00000], precision=[0.00000, 0.00000, 0.00000], hit=[0.00000, 0.00000, 0.00000], ndcg=[0.00000, 0.00000, 0.00000] 2023-03-23 22:09: #####Early stopping steps: 34 ##### (I only change the 'early_stopping_patience', all the codes are the same as that on the repository) Can you help me?

I'm sorry, but I can guarantee that our results were obtained by spending a lot of time doing experiments. No such blatant error is possible. To obtain good experimental results, people should try various parameter settings as much as possible. We recommend trying a grid search tool to adjust parameters: 'https://optuna.org/'.   If you do not obtain reasonable experimental results after various attempts, please tell us your experimental parameters at the time. We will check the experimental results under that setting, try to find the cause of the problem, and try to give helpful suggestions.

We appreciate your attention to our work, and we will try our best to respond to your sincere requests.

**Comment by shentt67** [comment]
> 

ok, thanks!
