### ISSUE TITLE
The file path of datasets

### ISSUE THREAD

**Issue by shentt67** [HKUDS/MMSSL#5]
Hi, Weiwei:
I debug the codes and find that I can't reproduce the result on Tiktok **because I am confused with the file path of the processed datasets on google drive.**
The file path of **Allrecipes** is easy to find. JSON files and Mat files are in the first level directory, and there are no other files and folders. So I reproduce the results successfully.
But the other three datasets are a little confusing **with many files and folders**. Can you show the path of JSON files and Mat files as the **Allrecipes** does?

**Allrecipes** is easy to find
![image](https://user-images.githubusercontent.com/68014311/228189231-13f8227c-ee5c-498f-8768-7a36a4e5721e.png)
but others are difficult for me to find:
![image](https://user-images.githubusercontent.com/68014311/228189554-fb17b02e-5f90-4257-80d9-27abc2f4924d.png)

**Comment by weiwei1206** [comment]
Sorry~, the reorganized data has also been uploaded a few days ago. And I reorganized the code again last night and deleted the useless code. 
You can just use the re-uploaded dataset.
