### ISSUE TITLE
A code error

### ISSUE THREAD

**Issue by shentt67** [HKUDS/MMSSL#7]
Hi, Weiwei, there may be a small error in the codes. In main.py:
![image](https://user-images.githubusercontent.com/68014311/228718943-6d4c9b9a-b133-4396-ad3d-22f236fdee15.png)
**Line 453**, the first param of the **test** function should be **users_to_val**.
Now I reproduce the results successfully. Thanks for your careful and patient answer!

**Comment by weiwei1206** [comment]
We appreciate your interest in our work and wish you luck with your work~

Best Regards,

WEI
