### ISSUE TITLE
Question about no acoustic modal

### ISSUE THREAD

**Issue by laohanlin** [HKUDS/MMSSL#8]
Hi, Weiwei, I noticed that the performance of MMSSL on Tiktok dataset using the acoustic modal in the paper. Hoever, the code only contains the text and image modal. Is the code not yet released on TikTok dataset?

**Comment by weiwei1206** [comment]
The code version on the Tiktok dataset has not been released yet. An alternative approach is to directly copy the code blocks of image and text to achieve more modular versions. Another more flexible approach is to maintain a dictionary for modalities, and then use a 'for' loop in the parts that involve multiple modalities. 

We apologize for any inconvenience caused. Following the solutions provided above is one way to resolve the issue. After well organizing the code properly, we will upload the TikTok version. 

Best Regards.
